Pin to an older version of the example alpine builder
In CI a `pack build` is performed using one of libcnb's example CNBs
and the upstream `cnb/sample-builder:alpine` builder, in order to test
that our static MUSL compile works with non-libc base images.

However, CI has just started failing with:

```
ERROR: failed to build: experimental features must be enabled when builder contains image extensions
```
(https://github.com/heroku/libcnb.rs/actions/runs/5530837180/jobs/10090742723?pr=592#step:10:107)

This is due to the upstream images having been rebuilt with extension
support, which is an experimental feature until the next stable Pack CLI
release):
https://github.com/buildpacks/samples/pull/149
https://github.com/buildpacks/samples/pull/142

As such until Pack CLI v0.30 is released as stable, we'll have to pin
to an older `alpine` image by SHA256 ref.

GUS-W-13746154.