Update otel crates  (#955)
* Bump the opentelemetry group across 1 directory with 4 updates

Updates the requirements on [opentelemetry](https://github.com/open-telemetry/opentelemetry-rust), [opentelemetry_sdk](https://github.com/open-telemetry/opentelemetry-rust), [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-rust) and [tracing-opentelemetry](https://github.com/tokio-rs/tracing-opentelemetry) to permit the latest version.

Updates `opentelemetry` to 0.29.0
- [Release notes](https://github.com/open-telemetry/opentelemetry-rust/releases)
- [Commits](https://github.com/open-telemetry/opentelemetry-rust/compare/opentelemetry-0.28.0...opentelemetry-0.29.0)

Updates `opentelemetry_sdk` to 0.29.0
- [Release notes](https://github.com/open-telemetry/opentelemetry-rust/releases)
- [Commits](https://github.com/open-telemetry/opentelemetry-rust/compare/opentelemetry_sdk-0.28.0...opentelemetry_sdk-0.29.0)

Updates `opentelemetry-proto` to 0.29.0
- [Release notes](https://github.com/open-telemetry/opentelemetry-rust/releases)
- [Commits](https://github.com/open-telemetry/opentelemetry-rust/compare/opentelemetry-proto-0.28.0...opentelemetry-proto-0.29.0)

Updates `tracing-opentelemetry` to 0.30.0
- [Release notes](https://github.com/tokio-rs/tracing-opentelemetry/releases)
- [Changelog](https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/CHANGELOG.md)
- [Commits](https://github.com/tokio-rs/tracing-opentelemetry/compare/v0.29.0...v0.30.0)

---
updated-dependencies:
- dependency-name: opentelemetry
  dependency-version: 0.29.0
  dependency-type: direct:production
  dependency-group: opentelemetry
- dependency-name: opentelemetry_sdk
  dependency-version: 0.29.0
  dependency-type: direct:production
  dependency-group: opentelemetry
- dependency-name: opentelemetry-proto
  dependency-version: 0.29.0
  dependency-type: direct:production
  dependency-group: opentelemetry
- dependency-name: tracing-opentelemetry
  dependency-version: 0.30.0
  dependency-type: direct:production
  dependency-group: opentelemetry
...

Signed-off-by: dependabot[bot] <support@github.com>

* Fix interface

```
error[E0053]: method `export` has an incompatible type for trait
   --> libcnb/src/tracing.rs:143:9
    |
143 |         &mut self,
    |         ^^^^^^^^^ types differ in mutability
    |
    = note: expected signature `fn(&FileExporter<_>, Vec<_>) -> Pin<_>`
               found signature `fn(&mut FileExporter<_>, Vec<_>) -> Pin<_>`
help: change the self-receiver type to match the trait
    |
143 -         &mut self,
143 +         &self,
    |

```

* Fix compile error


```
  Compiling sha2 v0.10.9
projects/work/libcnb.rs/libcnb)
   Compiling libcnb-package v0.29.1 (/Users/rschneeman/Documents/projects/work/libcnb.rs/libcnb-package)
   Compiling ureq v3.0.12
warning: impl trait in impl method signature does not match trait method signature
   --> libcnb/src/tracing.rs:145:10
    |
145 |     ) -> BoxFuture<'static, OTelSdkResult> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: add `#[allow(refining_impl_trait)]` if it is intended for this to be part of the public API of this crate
    = note: we are soliciting feedback, see issue #121718 <https://github.com/rust-lang/rust/issues/121718> for more information
    = note: `#[warn(refining_impl_trait_internal)]` on by default
help: replace the return type so that it matches the trait
    |
145 -     ) -> BoxFuture<'static, OTelSdkResult> {
145 +     ) -> impl Future<Output = std::result::Result<(), OTelSdkError>> + Send {
    |

   Compiling libcnb-test v0.29.1 (/Users/rschneeman/Documents/projects/work/libcnb.rs/libcnb-test)
   Compiling libherokubuildpack v0.29.1 (/Users/rschneeman/Documents/projects/work/libcnb.rs/libherokubuildpack)
   Compiling libcnb-cargo v0.29.1 (/Users/rschneeman/Documents/projects/work/libcnb.rs/libcnb-cargo)
warning: `libcnb` (lib) generated 1 warning
   Compiling examples-execd v0.0.0 (/Users/rschneeman/Documents/projects/work/libcnb.rs/examples/execd)
   Compiling examples-basics v0.0.0 (/Users/rschneeman/Documents/projects/work/libcnb.rs/examples/basics)
```

* Changelog

* Fix clippy

```
$ cargo clippy
warning: extern crate `futures_core` is unused in crate `libcnb`
 --> libcnb/src/lib.rs:1:1
  |
1 | #![doc = include_str!("../README.md")]
  | ^
  |
  = help: remove the dependency or add `use futures_core as _;` to the crate root
  = note: requested on the command line with `-W unused-crate-dependencies`

warning: `libcnb` (lib) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.36s
```

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>