Update for breaking API changes
Fixes:

```
error[E0308]: mismatched types
  --> libcnb-package/src/cargo.rs:51:26
   |
51 |     target.kind.contains(&String::from("bin"))
   |                 -------- ^^^^^^^^^^^^^^^^^^^^ expected `&TargetKind`, found `&String`
   |                 |
   |                 arguments to this method are incorrect
   |
   = note: expected reference `&cargo_metadata::TargetKind`
              found reference `&std::string::String`
```

Due to:
https://github.com/oli-obk/cargo_metadata/pull/258

However, we can use this simpler API instead:
https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Target.html#method.is_bin