Allow ProcessTypes to be compared
While writing a build pack I wanted to test that an `Launch::r#type` was properly set and tried to use `assert_eq!`. To my surprise I found that it could not be compared:

```
error[E0369]: binary operation `==` cannot be applied to type `ProcessType`
   --> src/data/launch.rs:146:9
    |
146 |           assert_eq!(
    |  _________^
    | |_________|
    | |
147 | |             ProcessType::from_str("web").unwrap(),
148 | |             ProcessType::from_str("web").unwrap()
149 | |         )
    | |         ^
    | |_________|
    | |_________ProcessType
    |           ProcessType
```

This is fixed by setting the partial eq trait https://doc.rust-lang.org/std/cmp/trait.PartialEq.html. 

In addition I added `Eq` trait as the objects have an Equivalence relation as well.