Update Store derives
## Store cannot be cloned 

I want to have write some code like this:

```rust
        let store = context.store.get_or_insert_with(|| {
            let mut rng = rand::thread_rng();
            let value = (0..64)
                .map(|_| rng.sample(rand::distributions::Alphanumeric) as char)
                .collect::<String>();

            let mut metadata = toml::value::Table::default();
            metadata.insert(String::from("SECRET_KEY_BASE"), value.into());

            Store { metadata }
        });
```

But I can't since the store isn't mutable and I cannot clone it:

```

   Compiling heroku-ruby-buildpack v0.0.0 (/Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/buildpacks/ruby)
warning: unused variable: `store`
   --> buildpacks/ruby/src/main.rs:117:13
    |
117 |         let store = context.store.get_or_insert_with(|| {
    |             ^^^^^ help: if this is intentional, prefix it with an underscore: `_store`
    |
    = note: `#[warn(unused_variables)]` on by default

error[E0596]: cannot borrow `context.store` as mutable, as `context` is not declared as mutable
   --> buildpacks/ruby/src/main.rs:117:21
    |
65  |       fn build(&self, context: BuildContext<Self>) -> libcnb::Result<BuildResult, Self::Error> {
    |                       ------- help: consider changing this to be mutable: `mut context`
...
117 |           let store = context.store.get_or_insert_with(|| {
    |  _____________________^
118 | |             let mut rng = rand::thread_rng();
119 | |             let value = (0..64)
120 | |                 .map(|_| rng.sample(rand::distributions::Alphanumeric) as char)
...   |
126 | |             Store { metadata }
127 | |         });
    | |__________^ cannot borrow as mutable

For more information about this error, try `rustc --explain E0596`.
warning: `heroku-ruby-buildpack` (bin "heroku-ruby-buildpack") generated 1 warning (1 duplicate)
error: could not compile `heroku-ruby-buildpack` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
warning: `heroku-ruby-buildpack` (bin "heroku-ruby-buildpack" test) generated 1 warning
error: could not compile `heroku-ruby-buildpack` due to previous error; 1 warning emitted
[Finished running. Exit status: 101]
```

I'm able to extract the metadata and work on that directly, but I would rather maintain and manipulate Store directly.

```rust
        let mut metadata = match context.store {
            Some(store) => store.metadata,
            None => toml::value::Table::default(),
        }
        .clone();

        metadata.entry("SECRET_KEY_BASE").or_insert_with(|| {
            let mut rng = rand::thread_rng();

            (0..64)
                .map(|_| rng.sample(rand::distributions::Alphanumeric) as char)
                .collect::<String>()
                .into()
        });
```


## Store has no default

Not a big deal if it's not there, but Option has a `get_or_default` in nightly and it would be neat to be able to `context.store.get_or_default` when that is stable.