Fix libcnb-tests's integration tests with newer Rosetta/Docker Desktop
libcnb-test's own integration tests were failing locally when run using
newer versions of Docker Desktop and/or the Rosetta feature in
macOS 14.1.

Rosetta now creates a `$HOME/.cache/rosetta` directory that was breaking
the directory listing assertions in the `app_dir_preprocessor` test:

```
---- app_dir_preprocessor stdout ----
thread 'app_dir_preprocessor' panicked at libcnb-test/tests/integration_test.rs:189:13:
assertion `left == right` failed
  left: ".\n./.cache\n./.cache/rosetta\n./Procfile\n./subdir1\n./subdir1/file2.txt\n./subdir1/subdir2\n./subdir1/subdir2/subdir3\n./subdir1/subdir2/subdir3/file3.txt\n"
 right: ".\n./Procfile\n./subdir1\n./subdir1/file2.txt\n./subdir1/subdir2\n./subdir1/subdir2/subdir3\n./subdir1/subdir2/subdir3/file3.txt\n"
```

In addition, it seems the newer Docker daemon now supports port 0,
which was the port used by the `expose_port_invalid_port` test. There
isn't another bogus port we can use (since the data types use an unsigned
16 bit int, whose max value is the same as the max port allowed - so we
can't use a port like 99999), and the test itself is somewhat redundant,
since failing `start_container()` is already tested in other ways.

As such the `expose_port_invalid_port` test has been removed.

Fixes #706.
GUS-W-14395756.