Fix auto PATH ordering (#938)
* Failing test for #900

* Add a delimiter to the path

Missing delimiter strikes again

* Fix auto PATH ordering

In #900, I observed that the path of a layer's `./bin` dir (if present) is appended to any explicitly added paths by CNB lifecycle. Libcnb instead prepends the path.

This is fixed to match the upstream implementation by changing the order of path evaluation.

Close #900

* Test Build and Launch scope

* Expected before actual in assertion

* Test LIBRARY_PATH ordering

* Changelog

* Doc whitespace and headers

* Update docs s/append/prepend/

The docs stated that we're appending the layer-bin path. With this change we're now prepending it to align with lifecycle.

* Simplify layer_paths_come_before_manually_added_paths test

* Emit scope and path on failure

Before:

```
thread 'layer_env::tests::layer_paths_come_before_manually_added_paths' panicked at libcnb/src/layer_env.rs:944:13:
assertion `left == right` failed
  left: Some("/var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/.tmpKPAfq0/bin:test-value")
 right: Some("test-value/var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/.tmpKPAfq0/bin")
```

After:

```
thread 'layer_env::tests::layer_paths_come_before_manually_added_paths' panicked at libcnb/src/layer_env.rs:944:13:
assertion `left == right` failed: For ENV var `PATH` scope `Build`
  left: Some("/var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/.tmpaCmToR/bin:test-value")
 right: Some("test-value/var/folders/yr/yytf3z3n3q336f1tj2b2j0gw0000gn/T/.tmpaCmToR/bin")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

* Apply suggestions from code review

Co-authored-by: Manuel Fuchs <manuel.fuchs@salesforce.com>
Signed-off-by: Richard Schneeman <richard.schneeman+no-recruiters@gmail.com>

---------

Signed-off-by: Richard Schneeman <richard.schneeman+no-recruiters@gmail.com>
Co-authored-by: Manuel Fuchs <manuel.fuchs@salesforce.com>