Use the multi-line `$GITHUB_OUTPUT` syntax for the changelog entry output
The changelog entry is multi-line, so we need to use the multi-line syntax
when using the `$GITHUB_OUTPUT` file.

This resolves:

```
Error: Unable to process file command 'output' successfully.
Error: Invalid format '### Added'
```

See:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

GUS-W-14177169.