Fail tests early if cross-compilation toolchains are missing
For platforms where the cross-compilation assistance feature knows
which tools are required, tests will now fail early with a clearer error
message if those tools are not found.

For example:

```
$ cargo test basic -- --ignored
test basic ... FAILED

failures:

---- basic stdout ----
thread 'basic' panicked at 'Could not package current crate as buildpack: CrossCompileConfigurationError("For cross-compilation from macOS to x86_64-unknown-linux-musl, a C compiler and\nlinker for the target platform must be installed on your computer.\n\nThe easiest way to install the required cross-compilation toolchain is to run:\nbrew install messense/macos-cross-toolchains/x86_64-unknown-linux-musl\n\nFor more information, see:\nhttps://github.com/messense/homebrew-macos-cross-toolchains")', /Users/emorley/src/libcnb.rs/libcnb-test/src/lib.rs:177:22
```

The output does contain escaped newlines, however so will many other failure
modes - since `IntegrationTest::run_test()` uses `.expect()` (which prints the
debug representation of any returned `Error`s), and improving that is outside
the scope of this issue.

Fixes #340.