Update cargo_metadata requirement from 0.18.1 to 0.19.1 (#889)
* Update cargo_metadata requirement from 0.18.1 to 0.19.1

Updates the requirements on [cargo_metadata](https://github.com/oli-obk/cargo_metadata) to permit the latest version.
- [Release notes](https://github.com/oli-obk/cargo_metadata/releases)
- [Changelog](https://github.com/oli-obk/cargo_metadata/blob/main/CHANGELOG.md)
- [Commits](https://github.com/oli-obk/cargo_metadata/compare/0.18.1...0.19.1)

---
updated-dependencies:
- dependency-name: cargo_metadata
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Update for breaking API changes

Fixes:

```
error[E0308]: mismatched types
  --> libcnb-package/src/cargo.rs:51:26
   |
51 |     target.kind.contains(&String::from("bin"))
   |                 -------- ^^^^^^^^^^^^^^^^^^^^ expected `&TargetKind`, found `&String`
   |                 |
   |                 arguments to this method are incorrect
   |
   = note: expected reference `&cargo_metadata::TargetKind`
              found reference `&std::string::String`
```

Due to:
https://github.com/oli-obk/cargo_metadata/pull/258

However, we can use this simpler API instead:
https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.Target.html#method.is_bin

* Inline `is_binary_target`

Since it's only used once and its implementation is now trivial.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>