Improve the error message shown when Pack CLI is not installed
Before:
```
---- basic_build stdout ----
thread 'basic_build' panicked at 'Could not spawn external 'pack' process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/emorley/src/libcnb.rs/libcnb-test/src/test_runner.rs:188:14
```

After:
```
---- basic_build stdout ----
thread 'basic_build' panicked at 'External `pack` command not found. Install Pack CLI and ensure it is on PATH: https://buildpacks.io/docs/install-pack', /Users/emorley/src/libcnb.rs/libcnb-test/src/test_runner.rs:184:21
```

No integration test has been added, since writing one would
involve manipulating the `PATH` of the integration test process
which would be prone to intermittent test failures given concurrent
execution.

In addition all panic messages that reference "pack" now do so inside
backticks rather than single quotes, since the panic error message itself
is inside single quotes, so it looked like the quoted section had ended
prematurely.

Fixes #296.
GUS-W-11390631.